### ISSUE TITLE
deb https://download.puffinbrowser.com/repo/ stable main useful?

### ISSUE THREAD

**Issue by jidanni** [ZhymabekRoman/Puffin-Browser-on-Linux#5]
Doing 
`dpkg -i /tmp/puffin-internet-terminal_demo.dpkg`
causes /etc/apt/sources.list.d/puffin-internet-terminal.list to get installed,
which just has the same as
https://raw.githubusercontent.com/ZhymabekRoman/Puffin-Browser-on-Linux/main/puffin-internet-terminal.list
namely
deb https://download.puffinbrowser.com/repo/ stable main
in it.

But if that line was useful to us, then we wouldn't need https://github.com/ZhymabekRoman/Puffin-Browser-on-Linux here on linux, no?

I mean if we could just install it from the Puffin corporation, then we wouldn't need this GitHub project, no?

I mean that file is probably useful for you, but not this GitHub's end users, no?

**Comment by ZhymabekRoman** [comment]
Yes, you can install Puffin directly from the official repository. See first install method from README.md - [link](https://github.com/ZhymabekRoman/Puffin-Browser-on-Linux#first-method---by-adding-puffin-repositories-to-the-system). But sometimes (in some distros like Mint) the first installation method doesn't work, so I've uploaded deb packages to GitHub so that Mint users can install Puffin from the deb package.

**Comment by jidanni** [comment]
(OK, I tried the official one. The browser launches but then one is supposed to sign up. It asks for an activation code...
We first enter our email... "Your mail is not registered to use Puffin Browser." So we are supposed to $ub$cribe.  OK, never mind that version. I'll stick to your version.  Hmmm, too bad we have to clean up /etc/apt by hand.)

**Comment by ZhymabekRoman** [comment]
Most likely you have installed the Pro version, not the Demo version. Pro version requires subscription, Demo doesn't
